// NOTE This file is auto-generated! Do not edit, as all changes will be overwritten!
.pragma library

var weatherSymbolDescription = {
    "101": qsTr("clear"),
    "102": qsTr("slightly overcast"),
    "103": qsTr("heavy cloud formations"),
    "104": qsTr("overcast"),
    "105": qsTr("very cloudy"),
    "106": qsTr("overcast, scattered showers"),
    "107": qsTr("overcast, scattered rain and snow showers"),
    "108": qsTr("overcast, snow showers"),
    "109": qsTr("overcast, some showers"),
    "10": qsTr("overcast, some sleet"),
    "110": qsTr("overcast, some rain and snow showers"),
    "111": qsTr("overcast, some snow showers"),
    "112": qsTr("slightly stormy"),
    "113": qsTr("storms"),
    "114": qsTr("very cloudy, light rain"),
    "115": qsTr("very cloudy, light rain and snow  showers"),
    "116": qsTr("very cloudy, light snowfall"),
    "117": qsTr("very cloudy, intermittent rain"),
    "118": qsTr("very cloudy, intermittant mixed rain and snowfall"),
    "119": qsTr("very cloudy, intermittent snowfall"),
    "11": qsTr("overcast, some snow showers"),
    "120": qsTr("very cloudy,  constant rain"),
    "121": qsTr("very cloudy, frequent rain and snowfall"),
    "122": qsTr("very cloudy, heavy snowfall"),
    "123": qsTr("very cloudy, slightly stormy"),
    "124": qsTr("very cloudy, stormy"),
    "125": qsTr("very cloudy, storms"),
    "126": qsTr("high cloud"),
    "127": qsTr("stratus"),
    "128": qsTr("fog"),
    "129": qsTr("slightly overcast, scattered showers"),
    "12": qsTr("sunny intervals, chance of thunderstorms"),
    "130": qsTr("slightly overcast, scattered snowfall"),
    "131": qsTr("slightly overcast, rain and snow showers"),
    "132": qsTr("slightly overcast, some showers"),
    "133": qsTr("overcast, frequent snow showers"),
    "134": qsTr("overcast, frequent snow showers"),
    "135": qsTr("overcast and dry"),
    "13": qsTr("sunny intervals, possible thunderstorms"),
    "14": qsTr("very cloudy, light rain"),
    "15": qsTr("very cloudy, light sleet"),
    "16": qsTr("very cloudy, light snow showers"),
    "17": qsTr("very cloudy, intermittent rain"),
    "18": qsTr("very cloudy, intermittent sleet"),
    "19": qsTr("very cloudy, intermittent snow"),
    "1": qsTr("sunny"),
    "20": qsTr("very overcast with rain"),
    "21": qsTr("very overcast with frequent sleet"),
    "22": qsTr("very overcast with heavy snow"),
    "23": qsTr("very overcast, slight chance of storms"),
    "24": qsTr("very overcast with storms"),
    "25": qsTr("very cloudy, very stormy"),
    "26": qsTr("high clouds"),
    "27": qsTr("stratus"),
    "28": qsTr("fog"),
    "29": qsTr("sunny intervals, scattered showers"),
    "2": qsTr("mostly sunny, some clouds"),
    "30": qsTr("sunny intervals, scattered snow showers"),
    "31": qsTr("sunny intervals, scattered sleet"),
    "32": qsTr("sunny intervals, some showers"),
    "33": qsTr("short sunny intervals, frequent rain"),
    "34": qsTr("short sunny intervals, frequent snowfalls"),
    "35": qsTr("overcast and dry"),
    "3": qsTr("partly sunny, thick passing clouds"),
    "4": qsTr("overcast"),
    "5": qsTr("very cloudy"),
    "6": qsTr("sunny intervals,  isolated showers"),
    "7": qsTr("sunny intervals, isolated sleet"),
    "8": qsTr("sunny intervals, snow showers"),
}
